server.servlet.context-path=/authService

spring.application.name=auth-application
spring.profiles.active=oracleDB

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true

# Environment endpoint
management.endpoint.env.access=unrestricted

# Config Server
spring.config.import=optional:configserver:http://localhost:8092/

# Eureka
eureka.instance.preferIpAddress=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/

# Application information
info.app.name=auth-application
info.app.description=Retailers Hub Application's Authentication microservice
info.app.version=1.0.0

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000

#Grafana Props
management.tags.application=${spring.application.name}