server.servlet.context-path=/authService

spring.application.name=auth-application
spring.profiles.active=oracleDB

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted

# Environment endpoint
management.endpoint.env.access=unrestricted

# Config Server
spring.config.import=optional:configserver:http://localhost:8092/

# Eureka
eureka.instance.preferIpAddress=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/

# Application information
info.app.name=auth-application
info.app.description=Retailers Hub Application's Authentication microservice
info.app.version=1.0.0