spring.application.name=AuthenticationService
server.servlet.context-path=/authService
spring.profiles.active=myNewDB
userServiceBaseUrl=http://localhost:8088/userService
#springdoc-swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
notificationServiceBaseUrl=http://localhost:8090
#http://localhost:8089/authService/swagger-ui/index.html
#http://localhost:8089/authService/v3/api-docs
