spring:
  application:
    name: RetailersHubConfigServer

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-location: classpath:/config

server:
  port: 8092