spring.application.name=userservice-application
server.servlet.context-path=/userService
endpoints.shutdown.enabled=true
spring.profiles.active=oracleDB
management.endpoints.web.exposure.include=*
management.endpoints.shutdown.enabled=true
management.env.enabled=true
spring.config.import=optional:configserver:http://localhost:8092/
#notificationServiceBaseUrl=http://localhost:8090/
#springdoc-swagger-ui.path=/swagger-ui/index.html
#springdoc.api-docs.path=/api-docs
#http://localhost:8089/authService/swagger-ui/index.html
#http://localhost:8089/authService/v3/api-docs
#spring.config.import=configserver:http://host.docker.internal:8092/
eureka.instance.preferIpAddress=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/
info.app.name=auth-application
info.app.description=Retailers Hub Application's User microservice
info.app.version=1.0.0
