spring:
  application:
    name: notification-application

  profiles:
    active: mysqlDB1

  config:
    import: "optional:configserver:http://localhost:8092/"

management:
  endpoints:
    web:
      exposure:
        include: "*"